### ISSUE TITLE
Mouser BOM has several issues that need to be corrected 

### ISSUE THREAD

**Issue by hexbus** [skiselev/micro_8088#6]
11 items have minimum order quantities of 2000 and need to be updated as of November 2021.

There are also several SKUs that are obsolete and some unavailable.  These will have to be substituted or ordered elsewhere.

Also, there are about four backordered, likely due to the chip shortage, and will need to be procured elsewhere.

**Comment by skiselev** [comment]
Not sure if it is a "bug" per se. The components availability changes and it is difficult for me to maintain an up to date BOM. I treat it more as a list of suggested components. Next time, if you like, consider contributing - fix the issue and create a pull request.
Nevertheless, I've updated the BOM with components that are commonly available from Mouser in single quantities. I also replaced DIP sockets with Amphenol ones, that are very similar to previous 3M sockets, but a bit cheaper.
Note that there is still one component in the BOM - trimmer capacitor, which is not available from Mouser. I've added a note to the BOM saying that it is optional and can be replaced with a regular ceramic capacitor
Also there are 5 components that are backordered. I believe for most of them there are alternatives available, so just look around:
* 4606X-101-472LF resistor array can be replaced with 4606X-AP1-472LF which is exactly the same part, but in "ammo-pak" instead of bulk pack
* There are at least two available alternatives for PN2222A transistor, and that can be also replaced with other NPN BJT transistors, such as 2N3904
* Instead of the LTL-4231NHBP LED indicator with housing, a regular 3 mm LED can be used
* Instead of the currently unavailable 5 position DIP switch, any other 5 position DIP switch can be used
* Finally, instead of the CP80C88-2Z CPU, any other 8-10 MHz 8088, 80C88, one NEC V20 CPU can be used.
